server:
  port: 8091
spring:
  cloud:
    nacos:
      discovery:
        server‐addr: 127.0.0.1:8848
        namespace: public
        #cluster‐name: provider
        username: nacos
        password: nacos
  kafka:
    bootstrap-servers: 172.1.10.100:9092
    #bootstrap-servers: 172.16.15.100:9092
    #bootstrap-servers: 192.168.1.100:9092
    #bootstrap-servers: 172.1.11.100:9092
    #bootstrap-servers: 192.168.72.100:9092
  #  zipkin:
  #    base-url: http://172.16.15.100:9411
  #  kafka:
  #    bootstrap-servers: 192.168.1.130:9092
  #  #链路配置
  zipkin:
    base-url: http://127.0.0.1:9411
    sender:
      type: kafka
  sleuth:
    sampler:
      probability: 1.0
  application:
    name: provider-one-server
    logyname: sungrid
    appname: PROVIDER-ONE-SERVER
  #zipkin服务所在地址
#  zipkin:
#    base-url: http://localhost:9411/
#    discovery-client-enabled: true
#  #配置采样百分比,开发环境可以设置为1，表示全部，生产就用默认
#  sleuth:
#    sampler:
#      probability: 1

eureka:
  # 自定义应用服务在eureka中的实例名称
  instance:
    # eureka中的应用服务实例名称定义(配置后Eureka Server处显示,不配置显示默认注册名)
    instance-id: ${spring.application.name}:${server.port}
    ip-address: 127.0.0.1
    # 访问路径可以显示IP地址
    prefer-ip-address: true
  client:
    registerWithEureka: true # 单点的时候设置为 false 禁止注册自身
    fetchRegistry: true # 单点的时候设置为不拉取服务注册列表数据
    serviceUrl:
      defaultZone: http://127.0.0.1:8083/eureka/
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 127.0.0.1:8848 #配置Nacos的服务地址

swagger2:
  #在线文档标题
  title: sungrid在线接口文档
  #在线文档描述信息
  description: 核心服务
  #接口包扫描路径
  base-package: com.sunyard